# Generated by Django 4.2.7 on 2024-02-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='company_email',
        ),
    ]
