# Generated by Django 4.2.7 on 2024-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_userdetails_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='company_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
