# Generated by Django 4.2.7 on 2024-02-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_company_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
