# Generated by Django 4.2.7 on 2024-02-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetailstwo',
        ),
    ]
