# Generated by Django 4.2.7 on 2024-02-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_delete_userdetailstwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_login_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_login_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='no_of_times_login',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='document_proof',
            field=models.FileField(upload_to='images/'),
        ),
    ]
