# Generated by Django 4.2.7 on 2024-02-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_company_company_location_and_more'),
        ('adminapp', '0008_company_date_time_company_user_status'),
    ]

    operations = [
    ]
