# Generated by Django 4.2.7 on 2024-02-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_merge_20240219_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_status',
        ),
    ]
