# Generated by Django 4.2.7 on 2024-02-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_company_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_time',
        ),
    ]
