# Generated by Django 4.2.7 on 2024-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_company_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(max_length=255)),
                ('security_email', models.EmailField(max_length=254)),
                ('security_contact', models.CharField(max_length=20)),
                ('security_document_proof', models.FileField(upload_to='security_documents/')),
                ('security_password', models.CharField(max_length=255)),
                ('security_last_login_time', models.TimeField(null=True)),
                ('security_last_login_date', models.DateField(auto_now_add=True, null=True)),
                ('security_no_of_times_login', models.IntegerField(default=0, null=True)),
                ('security_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
