# Generated by Django 4.2.7 on 2024-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_carnumber_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='user_status',
            field=models.CharField(default='Authorized', max_length=50),
        ),
    ]
